name: Logical Dependency Demo

on: push

jobs:
  deploy-job:
    runs-on: ubuntu-latest
    # BUG: This job demands that "lint-job" finishes first.
    # But "lint-job" doesn't exist anywhere in this file!
    needs: [build-job, lint-job] 
    steps:
      - name: Deploying App
        run: echo "Deploying!"

  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Building App
        run: echo "Building!"
